stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - build

test:
  stage: test
  script:
    - cd $GOPATH/src/github.com/pogointel/opm
    - go test -v ./...

deploy:
  stage: deploy
  script:
  - deploy
  only:
  - develop
  tags:
  - gce
