stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - rm -rf $GOPATH/src/github.com/pogointel
    - mkdir -p $GOPATH/src/github.com/pogointel/
    - mv $CI_PROJECT_DIR $GOPATH/src/github.com/pogointel/
    - cd $GOPATH/src/github.com/pogointel/opm
    - go get -t ./...
    - buildscripts/linux/testbuild.sh
    - mkdir -p $CI_PROJECT_DIR

test:
  stage: test
  script:
    - cd $GOPATH/src/github.com/pogointel/opm
    - go test

deploy:
  stage: deploy
  script:
  - cd $GOPATH/bin
  - gsutil -m rsync -rdx "\..*" ./ gs://opm-binaries/
  - gcloud compute ssh opm-apiserver-2 --zone us-east1-b --command "sudo gsutil -m rsync -rd gs://opm-binaries/ /go/bin/"
  - gcloud compute ssh opm-scanner-2 --zone us-east1-b --command "sudo gsutil -m rsync -rd gs://opm-binaries/ /go/bin/"
  - gcloud compute ssh opm-proxyhub-2 --zone us-east1-b --command "sudo gsutil -m rsync -rd gs://opm-binaries/ /go/bin/"
  - gcloud compute ssh opm-apiserver-2 --zone us-east1-b --command "sudo systemctl restart apiserver"
  - gcloud compute ssh opm-scanner-2 --zone us-east1-b --command "sudo systemctl restart scanner"
  - gcloud compute ssh opm-proxyhub-2 --zone us-east1-b --command "sudo systemctl restart proxyhub"
  only:
  - develop
  tags:
  - gce
