stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - rm -rf $GOPATH/src/github.com/pogointel
    - mkdir -p $GOPATH/src/github.com/pogointel/
    - mv $CI_PROJECT_DIR $GOPATH/src/github.com/pogointel/
    - cd $GOPATH/src/github.com/pogointel/opm
    - go get -t ./...
    - buildscripts/linux/testbuild.sh

test:
  stage: test
  script:
    - cd $GOPATH/src/github.com/pogointel/opm
    - go test

deploy:
  stage: deploy
  script:
  - cd $GOPATH/bin
  - gsutil -m rsync -rdx "\..*" ./ gs://opm-binaries/
  - ssh opm-apiserver-2 -i ~/.ssh/google_compute_engine "sudo gsutil -m rsync -rd gs://opm-gitlabrunner/ /go/"
  - ssh opm-scanner-2 -i ~/.ssh/google_compute_engine "sudo gsutil -m rsync -rd gs://opm-gitlabrunner/ /go/"
  - ssh opm-proxyhub-2 -i ~/.ssh/google_compute_engine "sudo gsutil -m rsync -rd gs://opm-gitlabrunner/ /go/"
  - ssh opm-apiserver-2 -i ~/.ssh/google_compute_engine "sudo systemctl restart apiserver"
  - ssh opm-scanner-2 -i ~/.ssh/google_compute_engine "sudo systemctl restart scanner"
  - ssh opm-proxyhub-2 -i ~/.ssh/google_compute_engine "sudo systemctl restart proxyhub"
  only:
  - develop
  tags:
  - gce
